# Use postgres/example user/password credentials
version: '3.1'

services:
  java:
    build: ./
    depends_on:
        - db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/web_app_car_sales_db_innowise
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=12345
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: web_app_car_sales_db_innowise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
         - .:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080