create sequence car_id_seq;

alter sequence car_id_seq owner to postgres;

create table person
(
    id            integer generated by default as identity
        primary key,
    name          varchar(100) not null,
    year_of_birth integer      not null
        constraint person_year_of_birth_check
            check (year_of_birth > 1900),
    password      varchar(100) not null,
    role          varchar(100) not null
);

alter table person
    owner to postgres;

create table car_blank
(
    id                integer generated by default as identity
        constraint car_pkey
            primary key,
    name_of_car_blank varchar(200)  not null,
    year_of_release   integer
        constraint car_year_of_release_check
            check (year_of_release > 1768),
    description       varchar(1500) not null,
    cost              integer
        constraint car_cost_check
            check (cost > 1),
    person_id         integer
        references person
            on delete cascade,
    created_at        timestamp
);

alter table car_blank
    owner to postgres;

alter sequence car_id_seq owned by car_blank.id;

create unique index person_name_uindex
    on person (name);


